### ISSUE TITLE
Inheritance doesn't work as expected

### ISSUE THREAD

**Issue by leebrooks0** [paulelliott/fabrication#194]
I have a user fabricator and an instructor fabricator which inherits from the user fabricator, defined as per below:

``` rb
Fabricator(:user) do
  email { Faker::Internet.email }
  hashed_password 'password'
  role :customer
  created_at Time.now
  after_create { |user| user.profile = Fabricate(:profile) }
end

Fabricator(:instructor, from: :user) do
  role :instructor
end
```

If I inspect an instructor generated via: 

``` rb
puts Fabricate(:instructor).inspect
```

I get the below, and none of the other properties from the user fabricator have been set.

``` rb
<User @values={:role=>"instructor"}>
```

**Comment by dasheck0** [comment]
Is this still open? I get this behaviour/bug with fabrication gem 2.12.0 too.

**Comment by paulelliott** [comment]
This is still open. Fixing this requires a rewrite of the loading mechanism. It is a large amount of work for something that is easily worked around and only impacts a small number of users. I'll get to it eventually but it honestly hasn't been a priority.

Are you interested in taking a crack at it?
