### ISSUE TITLE
Adding explanation for hash values assignments

### ISSUE THREAD

**Issue by kuma-giyomu** [paulelliott/fabrication#202]
I had a case where I needed to assign a hash to an attribute. I instinctively did

``` ruby
Fabricator(:machine) do
  member {a:1}
end
```

which of course didn't work, spitting an error saying there was no such Fabricator for member. `schematics` says in this case that members has a proc value and {a:1} for params.
After thinking this through, it made sense since you can define values by blocks and you can pass options as well.

I tried

``` ruby
Fabricator(:machine) do
  member({a:1})
end
```

but it didn't turn out to work either since the value I pass is actually considered as parameters for the fabricator, which I find an unexpected behaviour.

In the end

``` ruby
Fabricator(:machine) do
  member {a:1}, nil
end
```

did get me what I was after, but I thought it might be worth describing this caveat on the official website (provided I have the correct solution).

MRI ruby 2.1.0
Fabrication 2.9.7

**Comment by joallard** [comment]
I'd suggest adding this to documentation in Defining Fabricators#Attributes, taking from @paulelliott's words:

> If you need to assign a Hash value to an attribute, you need to do so inside a block. Otherwise, Fabricate would treat is as he options argument to the fabricated attribute. (where you would normally define a count, custom fabricator, etc.)
>
>
> ```
> Fabricator(:person) do
>   name 'Greg Graffin'
>   settings do
>     {favorite_color: 'yellow', egg_preference: 'scrambled'}
>   end
> end
> ```

**Comment by paulelliott** [comment]
Good call, @joallard. I just added it to the docs.

https://github.com/paulelliott/fabrication-site/commit/9318c37fb6c82f7216803c32a4d7edd48b5ab3ec

Thanks!
