### ISSUE TITLE
Skip validation

### ISSUE THREAD

**Issue by asiniy** [paulelliott/fabrication#233]
Sometimes I need to skip the validation of my fabricated objects. How can I do it?

**Comment by paulelliott** [comment]
There is currently no way to do that within fabrication. In the instances where you need to do that, you could do it manually fairly easily though.

```
Fabricate.build(:thingy).save(validate: false)
```

**Comment by asiniy** [comment]
@paulelliott thanks. Can I commit that functionality to `fabrication`?

**Comment by paulelliott** [comment]
Mehta do you envision the API for that looking like?

On Saturday, January 3, 2015, Alex Antonov <notifications@github.com> wrote:

> @paulelliott <https://github.com/paulelliott> thanks. Can I commit that
> functionality to fabrication?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/paulelliott/fabrication/issues/233#issuecomment-68584437>
> .
>


-- 
Paul

**Comment by asiniy** [comment]
```
Fabricate.save_skipping_validation(:task)
```

**Comment by syntaxritual** [comment]
I think using `validate false` would be easier to remember, as several ORM's share this same save option.

**Comment by paulelliott** [comment]
@syntaxritual yeah, good point. So this:

```
Fabricator(:task) do
  validate false
  other 'stuff'
end
```

Would override the default value of `validate: true`. We could use a default transient for the validate field to make the implementation easier. Each ORM adapter would have to be made aware of it, too.

**Comment by asiniy** [comment]
@paulelliott please give me some time to develop this feature.

**Comment by mediatainment** [comment]
any news on that task?

**Comment by paulelliott** [comment]
No PRs for this although another change went in that prevents fabrication from validating models unless they are actually persisted.

So if you need to skip validation you can do this:

```
Fabricate.build(:my_model).save(validate: false)
```

...instead of...

```
Fabricate(:my_model)
```

I'm still open to a PR to add the shorthand if you're interested in making a contribution.

**Comment by wmadden** [comment]
@paulelliott fwiw I think it's better without the shorthand. It's a bit outside the scope of Fabrication.

**Comment by lmhsjackson** [comment]
I think it would be nice to have this. 
I tried to use the `Fabricate.build(:my_model).save(validate: false)` approach, but I have an after_create hook that I need. Is there a way of saying `after [:create, :build] do` ?
