### ISSUE TITLE
Does not persist fabricated has_many association?

### ISSUE THREAD

**Issue by andrewhavens** [paulelliott/fabrication#235]
I'm running into an issue trying to define a fabrication which has a `has_many` association. I'm using Fabrication version 2.11.3 and Mongoid 3.1.6.

```ruby
class Product
  include Mongoid::Document
  has_many :images, class_name: 'Product::Image', inverse_of: :product, dependent: :destroy
  # ...lots of other stuff
end

class Product::Image
  include Mongoid::Document
  belongs_to :product, inverse_of: :images, index: true
  # ...lots of other stuff
end

Fabricator :product do
  name { sequence(:title) { |i| "Test Product #{i}" } }
  description Faker::Lorem.sentence
end

Fabricator :product_with_images, from: :product do
  images count: 3, fabricator: :product_image
end

Fabricator :product_image, class_name: 'Product::Image' do
  product
  caption 'some caption'
  position { sequence(:position){|i| i} }
end

product = Fabricate(:product_with_images)
product.persisted? # true
product.images.length # 3
product.images.count # 0
product.images.first.persisted? # false
product.images.first.valid? # true
```

I'm not sure why this isn't working. Is it a bug?

**Comment by andrewhavens** [comment]
If I avoid using the Fabricator, I am able to create the associations manually:

```ruby
subject { Fabricate(:product) }
before do
  3.times { subject.images << Fabricate.build(:product_image) }
end
```

**Comment by paulelliott** [comment]
Can you post the definition of the `product_image` fabricator?

**Comment by andrewhavens** [comment]
@paulelliott Oops. Thought I did. I just updated my original post to include the `product_image` fabricator.

**Comment by paulelliott** [comment]
Pull `product` out of the `product_image` fabricator and see if that fixes it for you.

```
Fabricator :product_image, class_name: 'Product::Image' do
  caption 'some caption'
  position { sequence(:position){|i| i} }
end
```

**Comment by andrewhavens** [comment]
If I remove `product`, then I won't be able to `Fabricate(:product_image)` correctly. It will be missing the parent product that it belongs to.

**Comment by paulelliott** [comment]
It is very unusual to create an embedded document with mongoid without supplying the parent document. I've found in mongoid projects I've worked on in the past that we are always manually creating from the top down, so setting up references like that are typically unnecessary.

If you need to generate them that way, however, you could make an additional fabricator to facilitate that. Maybe something like this:

```
Fabricator :embeddable_product_image, from: :product_image do
  product nil
end
```

**Comment by andrewhavens** [comment]
This is not an embedded document. It's just a simple `has_many`/`belongs_to` relationship. I don't think that it's uncommon to define a factory/fabricator which specifies a default association. When I'm testing my `Product::Image`, I don't care about the details of the Product that it's associated with. So a fabricator like this works perfectly fine:

```ruby
Fabricator :product_image, class_name: 'Product::Image' do
  product
  caption 'some caption'
  position { sequence(:position){|i| i} }
end
```

Is it possible that this definition does not work because it does not know to pass itself as the parent?

```ruby
Fabricator :product_with_images, from: :product do
  images count: 3, fabricator: :product_image
end
```

**Comment by paulelliott** [comment]
Under the hood it generates an array of the related objects and sets it. What is happening here is it is creating extra parents and mongoid is getting confused about what to do.

You could alternatively rewrite your `:product_with_images` fabricator like this:

```
Fabricator :product_with_images, from: :product do
  images(count: 3) { Fabricate(:product_image, product: nil) }
end
```
