### ISSUE TITLE
Pluralized class names.

### ISSUE THREAD

**Issue by Exoth** [paulelliott/fabrication#238]
With fabrication 2.12.0 I can't define fabricators, with a pluralized `class_name`, as it tries to look for its singular variant:

    Fabrication::Support.class_for('Flights')
    Fabrication::UnfabricatableError: No class found for 'Flights' (original exception: uninitialized constant Flight)

There wasn't such a problem with 2.11.3:

    Fabrication::Support.class_for('Flights')
    Fabrication::UnfabricatableError: No class found for 'Flights' (original exception: uninitialized constant Flights)

**Comment by paulelliott** [comment]
In version 2.12.0 we changed that support method to use ActiveSupport's `classify` when it is available. This is to allow inflector configurations to also apply to Fabrication's class lookup.

**Comment by Exoth** [comment]
So is there a way now to specify a plural class name for a fabricator? This one became broken on 2.12.0:

Fabricator(:spec_localized_fallback_blanks, class_name: Spec::LocalizedFallbackBlanks)

**Comment by paulelliott** [comment]
In 2.12.0 there is not but I will be implementing a fix that will allow that to work correctly. If you specify the class_name explicitly, it will not do anything other than attempt to constantize it.

I have not done this work yet so in the mean time please lock your Gemfile down to `2.11.3`. I'll mark this issue as resolved once I push out the fix.

**Comment by Exoth** [comment]
Ok, thanks.

**Comment by beingmattlevy** [comment]
I was having the same issue. Thanks for taking a look. 
My example was changing Metadata to Metadatum

**Comment by paulelliott** [comment]
Just pushed 2.12.1 with a fix for this. Let me know if you have any other issues!

**Comment by paulelliott** [comment]
It will now attempt to constantize the class name as it is set when that attribute is explicitly provided. For example:

```
class Cats
end

Fabricator(:my_amazing_cats, class_name: 'Cats')
```

It will constantize `Cats` without doing any other modification. If it does not resolve to a class name, then it will fall back and massage it into something class-like.

**Comment by alexcavalli** [comment]
Ran into this same issue. Thanks for the quick fix!

One somewhat confusing thing though, the fabrication docs suggest using singular names for your fabricators:
```ruby
Fabricator(:person) do
  name 'Greg Graffin'
  profession 'Professor/Musician'
end
```

But the ```classify``` inflector doesn't handle singular names super well, as mentioned in [the AS docs](http://api.rubyonrails.org/classes/ActiveSupport/Inflector.html#method-i-classify):
> Singular names are not handled correctly:
```ruby
'calculus'.classify     # => "Calculu"
```

I guess for many singular fabricator names it'll just make no change, but for any that end in "s" it appears to drop the last "s" (my particular issue was "company_class" => CompanyClas). It will handle them correctly if the fabricator name is the pluralized version of the class name, but that runs contrary to the docs, hence my confusion. Maybe the [camelize](http://api.rubyonrails.org/classes/ActiveSupport/Inflector.html#method-i-camelize) inflector would be better for converting singular, underscored fabricator names to singular, class-ified versions? It should also work for the plurals -> Plurals issue mentioned originally in this thread.

```ruby
"flight".camelize # => "Flight"
"flights".camelize # => "Flights"
"metadata".camelize # => "Metadata"
"company_class".camelize # => "CompanyClass"
```

**Comment by beingmattlevy** [comment]
2.12.1 does not work for me.

**/Users/matt/.rvm/gems/ruby-2.1.5@betterdoctor-web/gems/fabrication-2.12.1/lib/fabrication/support.rb:13:in `rescue in class_for': No class found for 'BetterDoctor::Auth::LoginDetails' (original exception: uninitialized constant BetterDoctor::Auth::LoginDetail) (Fabrication::UnfabricatableError)**

The fabricator in question is as follows: 
```Ruby
Fabricator(:account_login_details, from: 'BetterDoctor::Auth::LoginDetails') do
  login_count 10
  last_login_at Time.now
  last_ip '127.0.0.1'
end
```

**Comment by paulelliott** [comment]
I thought the ActiveSupport classify stuff would make things better for most users but it is proving to have more of a negative impact than a positive one. Anyone have a problem with just reverting back to the original behavior?

**Comment by alexcavalli** [comment]
No objections from me.

**Comment by beingmattlevy** [comment]
+1 reverting behavior back to not use classify. I specify the model names very specifically. No need to use ActiveSupport classify for my application.

**Comment by paulelliott** [comment]
Just pushed version 2.12.2 with these changes reverted. Sorry about this!

**Comment by beingmattlevy** [comment]
Thanks for the change. I'll test it out.

**Comment by beingmattlevy** [comment]
2.12.2 works for me. Aces!
