### ISSUE TITLE
Option to Generate Fabricator Based on Existing Model

### ISSUE THREAD

**Issue by fny** [paulelliott/fabrication#240]
It would be nice if an option could be added to Fabrications model generator which will populate  attributes from an existing model by adding some kind of flag (e.g. `rails g fabrication:model SomeModel --copy`).

I've already got this working for AR models. Let me know if I should make a PR.

**Comment by paulelliott** [comment]
That is kind of an unusual use case. If you have multiple tables with the same fields, maybe they should be the same table?

I appreciate the work you've put into this, but I am not convinced it is valuable enough to the codebase to accept the debt that would come with it. If you disagree or want me to review what you've done, go ahead and make the PR and we can discuss it further there.
