### ISSUE TITLE
Easily fabricate objects with hash initializers

### ISSUE THREAD

**Issue by maxlinc** [paulelliott/fabrication#242]
I've been finding myself doing this a lot:

```ruby
Fabricator(:object_from_hash, from: MyObjectWithHashInitialization) do
  initialize_with { @_klass.new to_hash } # Initialize with a hash
  name { 'foo ' }
  url { 'http://www.google.com' }
end
```

This works pretty fairly well for many objects, but I run into problems if some of the properties are immutable - they can be set during initialization but don't cannot be updated. The problem is that Fabrication appears to be doing something like this:

```ruby
obj = MyObjectWithHashInitialization.new(name: 'foo', url: 'http://www.google.com')
obj.name = 'foo'
obj.url = 'http://www.google.com'
```

This is repetitive, but also causes a problem if `name` can only be set during initialization.

Is there a way to avoid this so that I'm using a hash-based initialization as an *alternative* to a no-args constructor + attribute assignment? I'm a bit confused by `initialize_with` vs `on_init` vs `init_with`, so I don't know if this is already possible or would be an enhancement.

**Comment by maxlinc** [comment]
I should note that I've been working around this with transients, but:
- It requires more code and makes it harder to use some features
- There seems to be a bug where calling to_hash actually clears the transients so they aren't useable in other callbacks.

**Comment by plicjo** [comment]
Forgive me if I'm stupid but you said, "I run into problems if some of the properties are immutable - they can be set during initialization but don't cannot be updated."

Isn't that the idea behind being immutable?

**Comment by maxlinc** [comment]
Yes. I was repeating myself (defining immutable). and saying I had trouble using fabrication with immutable fields.
