### ISSUE TITLE
Fabricator overriding association id attributes

### ISSUE THREAD

**Issue by Draiken** [paulelliott/fabrication#249]
So, I'm trying to upgrade Fabrication from an old version to the newest, thought it would go smoothly since the changelog doesn't show any big changes but I've got some failing tests. After some digging I found out that it was overriding some association's attributes. Here is an example:

    Fabricator :post do
      author # assume author fabricator
    end

    post = Fabricate(:post, author_id: 5)    
    post.author
    #=> #<Author:0x2131231>
    post.author_id
    # => 1

The correct behavior should be

    post = Fabricate(:post, author_id: 5)    
    post.author
    #=> nil
    post.author_id
    # => 5

On older versions, it worked as expected, it would see that I supplied the `author_id`, so the author should not be fabricated. But now it actually fabricates the author and overrides my `author_id`.

I've checked on `FactoryGirl` and they also do not override the attribute.

Unfortunately we were on a very old version (2.7.2), so I can't say at which point this behavior changed. I have not found this change documented on the changelog, but I believe the fabricator should be smart to know that if we're overriding the id reference to another fabricator, it shouldn't create the association and override it.

**Comment by paulelliott** [comment]
Any chance you are also upgrading your ORM? Fabrication is setting the author first and then the author_id and that has not changed since the 2.0 release.

**Comment by Draiken** [comment]
No, I'm just upgrading the fabrication gem.

I'll try reproducing this on a new rails app and get back to you.

**Comment by Draiken** [comment]
I've successfully reproduced the error on a brand new rails app. Here is a gist that will do it: https://gist.github.com/dbe1bd2af0d583c28d75

**Comment by paulelliott** [comment]
Yeah, that is what I would expect. Fabrication doesn't know anything about your actual model. All it knows is that you've asked it to set some attributes. Author and author_id are completely separate things as far as it is concerned.

When you specify both as in that gist, it sets the author first and then the author_id as you've specified them. Then it calls save, at which point the ORM decides which takes precedence. You could probably work around it with a transient though.

Fabricator(:author) do
  transient :author
  author
  author_id { |attrs| attrs[:author].try(:id) }
end

By specifying a transient fabrication will not actually set the author on the model it generates. Keep in mind that you cannot set an unsaved author with this code. It must have an id to work.
