### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by renemaya** [paulelliott/fabrication#257]
I use an app called Dash in mac which allows me to read the docs offline (useful when traveling). It also reads markdown files as guides. It would be awesome if you could add fabrication's [documentation](https://github.com/paulelliott/fabrication-site/blob/master/source/index.markdown) as a guide so we Dash users could have it as an offline reference. Cheers!

**Comment by paulelliott** [comment]
Sorry for the delayed response. I think this is a great idea. I don't really use dash anymore but the docs for packaging it up are here.

https://kapeli.com/docsets#dashDocset
