### ISSUE TITLE
Fabrication 2.13 breaks Pickle's adapter

### ISSUE THREAD

**Issue by LcLk** [paulelliott/fabrication#260]
[Pickle](https://github.com/ianwhite/pickle) (a gem used with Cucumber to easily create models using underlying factories or ORMs) has a low level adapter to integrate with Fabricator ([Adapter code](https://github.com/ianwhite/pickle/blob/master/lib/pickle/adapter.rb#L144)). This adapter used the `Fabrication::Schematic::definition#klass`  attribute, which was made protected in this [commit](https://github.com/paulelliott/fabrication/commit/77ae1308a4ab6ad0e52d868c52d3cb60400399b9#diff-290101e40f430f9ba3d6ec636eaa71eb).

I want to fix this and issue a pull request but I'm unsure whether to do it here or in the Pickle gem.
On the one hand the fix in Fabrication is simply to move the `klass` function to being public instead of protected. 
But it is Pickle that is integrating with Fabrication at a low level using a non-public API, so really the change should be made there.

If you are happy to accept a pull request for this issue please let me know, if not, I'll make one for the Pickle gem.

**Comment by paulelliott** [comment]
I think the change should be made in pickle. I'm not sure why it wants access to all the schematics. You can get through the day by using send to get the schematics.

**Comment by LcLk** [comment]
Thanks @paulelliott, shall be done.
