### ISSUE TITLE
Custom fabrication generator

### ISSUE THREAD

**Issue by DmitryKK** [paulelliott/fabrication#261]
Hi. I have the following problem. I have instances of a class that is not inherited from ActiveRecord::Base. I want to create a custom generator and connect it to those classes that I need. Is this possible and how to do this?

**Comment by paulelliott** [comment]
Sure is! Just create the fabricator the same way you would for an active record model. As long as it has attr_accessors for the fields it will just work.

**Comment by DmitryKK** [comment]
Not suitable for me. I have classes where objects are created in a very complex way, I need a separate generator for such classes, and a way to connect. Is this possible?

**Comment by paulelliott** [comment]
Yeah, you can do that. It sounds like you'll need to use the `on_init` callback. It will let you define a custom constructor for your object. Anything you need to set on the object that doesn't have an `attr_accessor` will need to be declared as a transient and applied in a callback. 

https://github.com/paulelliott/fabrication-site/blob/master/source/index.markdown#callbacks
