### ISSUE TITLE
How to automate creation of fabricators along with models

### ISSUE THREAD

**Issue by AlexVPopov** [paulelliott/fabrication#262]
I would like to be able to automate the creation of fabricators along with models. I am aware of the existence of [`fabrication-rails`](https://github.com/chalofa/fabrication-rails), but it seems no longer maintained.

So this is the current state:

* `rails g model Post title:string body:text` does not create `spec/fabricators/post_fabricator.rb`;
* running `rails g fabrication:model post` before the migration only creates an empty fabricator with no attributes;
* running `rails g fabrication:model post` after the migration creates a proper fabricator, but also with `created/updated_at` attributes, which I find an unwanted side effect.

Currently, I am using the third option and I manually remove the timestamps. Is there a better option? Also, where is the fabrication generator (`rails g fabrication:model`) documented?

Thank you.

**Comment by AlexVPopov** [comment]
Just after submitting the issue I found the answer [here](https://gist.github.com/monicao/9595465):

```ruby
# config/application.rb
config.generators do |g|
  g.fixture_replacement :fabrication, dir: 'spec/fabricators'
end
```

**Comment by AlexVPopov** [comment]
I am willing to make a PR to the documentation. Would you accept such a PR?

**Comment by AlexVPopov** [comment]
I am ashamed :worried: , all this is in the docs: http://www.fabricationgem.org/#rails. Sorry :blush:

**Comment by paulelliott** [comment]
No worries, it happens to the best of us. PRs are always welcome for the docs although they are located in another repo:

https://github.com/paulelliott/fabrication-site
