### ISSUE TITLE
Automatic creation of fabricators sets their belong_to association as a regular attribute

### ISSUE THREAD

**Issue by AlexVPopov** [paulelliott/fabrication#263]
Suppose the model `Brand` exists, one wants to generate the model Product and Fabrication is set as the fixtures system in `application.rb`. The following command:
```ruby
rails g model product name:string brand:references{required}
```
produces the following fabricator:
```ruby
Fabricator(:product) do
  name  "MyString"
  brand nil
end
```
Here brand is just a regular attribute. Shouldn't it look like this:
```ruby
Fabricator(:product) do
  brand  
  
  name  "MyString"
end
```
?

**Comment by paulelliott** [comment]
That's a good catch. The change likely needs to be made here:

https://github.com/paulelliott/fabrication/blob/master/lib/rails/generators/fabrication/model/model_generator.rb#L24-L26

Is that something you'd like to try fixing?

**Comment by AlexVPopov** [comment]
I am willing, but currently I am on a deadline and I cannot promise when I'll be able to submit a PR, because I am on a deadline right now. When I have a bit more time, I'll check back with this issue and if still unfixed, I will submit a PR.
