### ISSUE TITLE
Any plans to implement something like trait in FactoryGirl?

### ISSUE THREAD

**Issue by Liooo** [paulelliott/fabrication#266]
I understand there's inheritance but it'd be nice to have something like trait to be able to pick and set multiple sets of predefined values.

FactoryGirl trait example

```
factory :user do
  name "Friendly User"

  trait :male do
    name   "John Doe"
    gender "Male"
  end

  trait :admin do
    admin true
  end
end

# creates an admin user with gender "Male" and name "Jon Doe"
create(:user, :admin, :male)
```

**Comment by paulelliott** [comment]
I have no plans to implement traits. I don't think they are a particularly compelling feature. That has a lot to do with one's approach to testing though.
