### ISSUE TITLE
bug. before_validation run twice in method Fabricate

### ISSUE THREAD

**Issue by raykin** [paulelliott/fabrication#267]
Here is code sample
```ruby
class User < ActiveRecord::Base

  attr_accessor :counter

  before_validation :increase_counter, on: :create

  def increase_counter
    if @counter.nil?
      @counter = 1
    else
      @counter += 1
    end
  end
end
```
when run following in test
```ruby
Fabricate(:user)
```
the @counter becomes 2.
You can get a rails sample to reproduce the bug in [https://github.com/raykin/learn_rails/tree/before-validation-called-twice](https://github.com/raykin/learn_rails/tree/before-validation-called-twice). Run rake test:models, there will be one test failed and one passed.

After research the source code, I think i got the cause.
On this line [https://github.com/paulelliott/fabrication/blob/946303926fd5c2776a2ac6c0c58a348ff0071284/lib/fabrication/generator/base.rb#L22](https://github.com/paulelliott/fabrication/blob/946303926fd5c2776a2ac6c0c58a348ff0071284/lib/fabrication/generator/base.rb#L22) it call before_validation first by [https://github.com/paulelliott/fabrication/blob/946303926fd5c2776a2ac6c0c58a348ff0071284/lib/fabrication/generator/active_record.rb#L18](https://github.com/paulelliott/fabrication/blob/946303926fd5c2776a2ac6c0c58a348ff0071284/lib/fabrication/generator/active_record.rb#L18), then on line [https://github.com/paulelliott/fabrication/blob/946303926fd5c2776a2ac6c0c58a348ff0071284/lib/fabrication/generator/base.rb#L26](https://github.com/paulelliott/fabrication/blob/946303926fd5c2776a2ac6c0c58a348ff0071284/lib/fabrication/generator/base.rb#L26) it call before_validation again through [https://github.com/paulelliott/fabrication/blob/946303926fd5c2776a2ac6c0c58a348ff0071284/lib/fabrication/generator/base.rb#L94](https://github.com/paulelliott/fabrication/blob/946303926fd5c2776a2ac6c0c58a348ff0071284/lib/fabrication/generator/base.rb#L94)

I didn't use callbacks in fabricators, so doesn't understand why Fabrication need another group of callbacks. The problem is I doesn't find a possible solution to only disable before_validation in save! method in Rails. So we may need another solution to inject Fabrication's callbacks to fix this bug?

**Comment by paulelliott** [comment]
Interesting. Any chance you could make a PR with a failing test that demonstrates the issue?
