### ISSUE TITLE
Object is associated through belongs_to doesn't see the associated object

### ISSUE THREAD

**Issue by DmitryKK** [paulelliott/fabrication#271]
I have the following problem:

My fabricator:

```
Fabricator(:cat) do
  animal
  title Test
  ...
end
```

where

```
class Animal < ActiveRecord::Base
  has_many :cats
end
```
and

```
class Cat < ActiveRecord::Base
  belongs_to :animal
end
```

When I create object:

`cat = Fabricate(:cat)`

then:

```
cat.animal.cats
=> []

```
but if I do reload then everything is fine:

```
cat.reload
cat.animal.cats
=> [0] #<Cat:0x0055acb...
```

I think the problem is somewhere in the code of fabricator

**Comment by paulelliott** [comment]
This is actually an issue with how you're using ActiveRecord. The tldr is that you need to specify `inverse_of` for that to work.

```
class Animal < ActiveRecord::Base
  has_many :cats, inverse_of: :animal
end

class Cat < ActiveRecord::Base
  belongs_to :animal, inverse_of: :cats
end
```

You can read more about it in the Rails guide: http://guides.rubyonrails.org/association_basics.html

**Comment by DmitryKK** [comment]
I know about this option. But it does not solve the problem. The record is still loaded only after reload. Please open issue and check for problems yourself

**Comment by stevenharman** [comment]
I too am seeing this, even with the `inverse_of` options in place. A new Rails 5 app with latest Fabrication gem.
