### ISSUE TITLE
Feature Request: Fabricate with unique fields

### ISSUE THREAD

**Issue by janfrs** [paulelliott/fabrication#272]
Hi, I'm sorry to bump this again(#32)  but, I have runned into the same problems, I've made my monkey patch as well but could you maybe reconsider and implement this? If not what would you recommend me to do?!

**So... the problem:** You have a model you want to fabricate and it has its unique constraints. You fabricate one of those models and assign those unique fields with Faker::anything. So far, so good. Only when for a strike of thunder, Faker::anything returns the same thing as before and your test or whatever fails miserably... I don't think Faker should be responsible for ensuring it is giving unique stuff to me everytime. But I do think Fabricator should be able to be smart about this...

**Comment by paulelliott** [comment]
Have you considered using sequences either combined with or in lieu of faker for these situations?

http://www.fabricationgem.org/#sequences

**Comment by janfrs** [comment]
Yes, I have, but that just can't guarantee uniqueness. When you start a testing environment, the sequence will always be 0, (We clean the database everytime) as I know many people do...

**Comment by paulelliott** [comment]
I understand what the issue is but I'm not sure what I could do to reliably fix it. Any suggestions?

**Comment by janfrs** [comment]
How about
```
Fabricate(:model,unique_fields: [:field_one,:field_two], class: 'ModelClassName')
```

**Comment by paulelliott** [comment]
ok, but how am I supposed to actually guarantee uniqueness of those fields?

**Comment by janfrs** [comment]
What about fabricating an then call the validate method? if it doesn't, try to fabricate again...... not sure if that's a good approach, just throwing some brainstorm here

**Comment by janfrs** [comment]
Let me think a little about this, I'm being silly here... I'll figure something out

**Comment by janfrs** [comment]
@paulelliott I solved my problem using Fabricate.build()

**Comment by paulelliott** [comment]
Glad you got it worked out!
