### ISSUE TITLE
Will fabrication have stubbing feature?

### ISSUE THREAD

**Issue by oasisweng** [paulelliott/fabrication#276]
I really like the way to set up associated objects in Fabrication. But transitioning from Factory Girl, I was able to take advantage of its stubbing feature. (build_stubbed)

Will Fabrication implement this feature any time? Or is it already achievable?

**Comment by paulelliott** [comment]
I have no plans to implement a clone of `build_stubbed`. If you explain what you're trying to accomplish with it I can probably help you figure out how to pull it off though.
