### ISSUE TITLE
NoMethodError: undefined method `*' for nil:NilClass

### ISSUE THREAD

**Issue by MoZaitoun** [paulelliott/fabrication#282]
I'm using Rails 4, [Fabricate][1] and [Faker][2] Gems. And I'm trying to seed my database with (100 or so) **randomly** created objects (Order that contains up to 3 Ice Creams).

**models/ice_cream.rb**

      class IceCream < ActiveRecord::Base
        ...
        has_and_belongs_to_many :flavors
        has_many :added_extras
        has_many :extras, :through => :added_extras
        belongs_to :order
        ...
      end

**models/extra.rb**

      class Extra < ActiveRecord::Base
        ...
        has_many :added_extras
        has_many :extras, :through => :added_extras
        ...
      end

**order_fabricator.rb**

    Fabricator(:order) do
        user { User.offset(rand(User.count)).first }
        shift { Shift.offset(rand(Shift.count)).first }
        created_at { Faker::Date.backward(365) }
        ice_creams(rand: 3) { |attrs| Fabricate( :ice_cream, created_at: attrs[:created_at] ) }
        before_create do total ||= self.ice_creams.sum(:total_price) end
        discount { [0, 10, 15, 25].sample } 
        total_after_discount { |order| order[:total] -  ( (order[:total] * order[:discount]) / 100 ) }
        paid { [50, 100, 200].sample }
        remaining { |order| order[:paid] -  order[:total_after_discount] }
      end

**flavor_fabricator.rb**

      Fabricator(:ice_cream) do
        size { Size.offset(rand(Size.count)).first }
        basis { Basis.offset(rand(Basis.count)).first }
        sauce { Sauce.offset(rand(Sauce.count)).first }
        topping { Topping.offset(rand(Topping.count)).first }
        flavors { Flavor.all.sample(rand(1..2)) }
        extras { Extra.all.sample(rand(0..3)) }
        ice_cream_price { [15, 17, 18, 19, 20, 22].sample }
        extras_price { [5, 10, 15, 20 ].sample } 
        total_price { |attrs| attrs[:ice_cream_price] + attrs[:extras_price] }
        created_at { Faker::Date.backward(365) }
      end

I'm trying to get the order's :total to be the sum of all randomly created ice_creams_total, but it returns with the error..

    NoMethodError: undefined method `*' for nil:NilClass

**Comment by paulelliott** [comment]
Continued from SO question: http://stackoverflow.com/questions/39824629

**Comment by paulelliott** [comment]
So I was saying your `Order` ActiveRecord model should have that in it and you should remove it from the Fabricator. Your models should "know" how to calculate values like that from their related records.

```
class Order < ActiveRecord::Base
  ...

  before_create do
    self.total ||= ice_creams.sum(:total_price)
  end
end
```

**Comment by MoZaitoun** [comment]
I wonder if there is there is another way only through Fabrication?

**Comment by paulelliott** [comment]
Well sure. Just make sure `total` is listed *after* `ice_creams` and their values will be available.

```
Fabricator(:order) do
  user { User.offset(rand(User.count)).first }
  shift { Shift.offset(rand(Shift.count)).first }
  created_at { Faker::Date.backward(365) }
  ice_creams(rand: 3) { |attrs| Fabricate( :ice_cream, created_at: attrs[:created_at] ) }

  total { |attrs| attrs[:ice_creams].sum(:total_price) }

  discount { [0, 10, 15, 25].sample } 
  total_after_discount { |order| order[:total] -  ( (order[:total] * order[:discount]) / 100 ) }
  paid { [50, 100, 200].sample }
  remaining { |order| order[:paid] -  order[:total_after_discount] }
end
```

My point is you could simplify what you're doing with some OOP. If you want to specify everything through fabrication you certainly can but it feels like you're writing logic that should just be part of the models themselves.

**Comment by MoZaitoun** [comment]
It returns error 

> NoMethodError: undefined method `+' for #<IceCream:0x000000064b7188>

BTW: Thanks for the advice, I think I should've implement this earlier, But right now I'm relying on nested forms to create ice creams within the order form so I'm using js to calculate the total_prices of each ice_cream in real time then pass it to the order total (hidden field) .  Maybe my approach is wrong. I wish I can find someone to consult him about many things as I said before I'm a newbie and it's my first app ever.

**Comment by paulelliott** [comment]
Oh, sorry about that. You need to use symbol to proc since the ice creams are just a regular array in that instance. Notice the `&`.

```
  total { |attrs| attrs[:ice_creams].sum(&:total_price) }
```

I'm happy to help. If you're looking for some support while you're learning you might want to sign up for http://www.railsmentors.org. They'll pair you up with an experienced dev to help you out.

**Comment by MoZaitoun** [comment]
Thanks man, It's solved. You're the best
