### ISSUE TITLE
Configure fabricators directory

### ISSUE THREAD

**Issue by lobo-tuerto** [paulelliott/fabrication#284]
Rails 5 favors minitest.

The test directory created when using it is `test` not `spec`.

If you configure Rails to use Fabrication like this:

```
config.generators do |g|
  g.test_framework :minitest, spec: true, fixture_replacement: :fabrication
end
```

When generating a new model, it creates a `spec` directory with a lonely item in it: `fabricators`.

I think it'll be good if it somehow created the `fabricators` folder inside the existing `test` folder.

**Comment by paulelliott** [comment]
The fabrication doc site has a section on minitest explaining how to set up your generators with minitest.

https://www.fabricationgem.org/#rails

```
config.generators do |g|
  g.test_framework      :minitest, fixture_replacement: :fabrication
  g.fixture_replacement :fabrication, dir: "test/fabricators"
end
```
