### ISSUE TITLE
The https://www.fabricationgem.org isn't working

### ISSUE THREAD

**Issue by gudata** [paulelliott/fabrication#286]
Clicking on the Navigation link doesn't happen anything.

**Comment by paulelliott** [comment]
It seems to be working for me. What browser are you using?

**Comment by gudata** [comment]
It doesn't work on (shows only navigation menu, no content, no errors in js console)

    Chromium Version 55.0.2883.87 Built on Ubuntu , running on Ubuntu 16.04 (64-bit)

and it works great on google chrome.

**Comment by paulelliott** [comment]
The docsite has its own project (paulelliott/fabrication). I don't have an ubuntu machine handy but you're welcome to make a PR there to fix it if you'd like. If not I'll try to get to it next week.

**Comment by gudata** [comment]
when I start the docsite with middleman on localhost it works in chromium. 
I tried to replace the local application.js with the current production [application.js](https://www.fabricationgem.org/javascripts/application-ca2847bd.js) and it works also.

**Comment by paulelliott** [comment]
Can you try accessing the site again today and seeing if you still have the problem?

**Comment by gudata** [comment]
It works.
Shame of me.
I noticed that I have turned off the javascript of the browser :(
