### ISSUE TITLE
Why does Fabrication::Generator::Base#post_initialize exist?

### ISSUE THREAD

**Issue by janpieper** [paulelliott/fabrication#287]
The method isn't used, as far as I can see... Method is defined here: [lib/fabrication/generator/base.rb#L103](https://github.com/paulelliott/fabrication/blob/00f6ef488e45661c09f2527ab968f478da27330f/lib/fabrication/generator/base.rb#L103)

**Comment by paulelliott** [comment]
I'm sure there was a good reason 4 years ago when it was added? In any event, it isn't used now. Thanks for pointing that out!
