### ISSUE TITLE
Docs: defining fabricators for namespaced models

### ISSUE THREAD

**Issue by nruth** [paulelliott/fabrication#288]
https://github.com/paulelliott/fabrication/issues/223 suggests `Fabricator(:my_class, from: 'MyModule::MyClass')`. Is that the right way? 
Could it be added to https://www.fabricationgem.org/#defining-fabricators ?

**Comment by paulelliott** [comment]
It is the preferred way and certainly can be added. Would you like to make a PR to paulelliott/fabrication-site?

**Comment by nruth** [comment]
Sure, will do.
