### ISSUE TITLE
[Proposal]Custom return value

### ISSUE THREAD

**Issue by jacob-s-son** [paulelliott/fabrication#291]
### Background

Initially we had something that most Rails app have - a simple `users` table, and, hence, a fabricator for it. Due to new requirements, we separated `user` object into two entities - `user_accounts` and `user_#{type}_profiles}`.
To reduce compatibility issues and number of refactorings we did two things:
- Copied all login information to `user_accounts` table
- Split users between two profiles (reused the same ID from `users` table)
- Combined profiles together with accounts into a `users` view

### The issue

So when reading, `User` object is almost exactly the same as before. `User` fabricator on the other hand is a bit of an issue now. We used combination of `aliases` and `after_create` callback, so that `Fabricate(:user)` would create an account + default profile. The problem is though, we need the `User` object in those tests, so we ended up having something like this in our specs: `Fabricate(:#{profile_type}_user).#{profile_type}_user`). Kind of works, but it would be nice if it was possible to override the return value of the fabricator.

### The proposal

Introduce three new "callbacks" (not a callback really, but so is `initialize_with`):
- `on_build_return` - overrides return value when building
- `on_create_return` - overrides return value when creating
- `on_fabricate_return` - overrides return value if building or creating

If those are present we would evaluate that in the context of our `_instance` and return the result of that here:
- https://github.com/paulelliott/fabrication/blob/master/lib/fabrication/generator/base.rb#L16
and here:
- https://github.com/paulelliott/fabrication/blob/master/lib/fabrication/generator/base.rb#L28

### Other thoughts
-  I'd make a more specific one to take precedence over the more general one (`on_build/create_return` > `on_fabricate_return `)
-  Ideally they would be inheritable and overridable
-  Other uses: it's not the only place where we rely on a view to return enhanced object. So often if we want in the test to get the "view" version of the object we do this:
```ruby
let(:project) { Fabricate(:project).to_dashboard_project }
```
I'd generalise this use case as - "return related object after fabricating".

If it's something you would back, I will present a patch. Also feel free to make a suggestions or discuss some specifics of the solution.

**Comment by paulelliott** [comment]
So if I understand correctly you have a `User` PORO that encapsulates `UserAccount` and `UserXProfile` ActiveRecord objects, correct?

Can you share the actual content of the fabricator you're trying to use? I think you actually can accomplish what you're trying to do with fabrication as it is without adding this new functionality.

**Comment by jacob-s-son** [comment]
@paulelliott not exactly - `User` in our case is a **read-only** `ActiveRecord` object, that is read from a SQL view. A single row in `users` view consists of combination of a `user_account` and `user_profile`.

Basically what we need is a new `User` fabricator, that:
-  creates two objects - `UserAccount` and `UserProfile`
-  queries `users` view for a read-only `User` object and returns it as a result of Fabrication

### Technical details

Below is what we have so far after starting refactoring. 

**AR classes**
```ruby
class UserAccount < ActiveRecord::Base
  #...
  has_one :buyer_profile, class_name: 'UserBuyerProfile', dependent: :destroy
  has_one :supplier_profile, class_name: 'UserSupplierProfile', dependent: :destroy
  # this is not 100% done, as one account will have more than 1 profile eventually
  # but for simplicity sake, let's assume there is a single user record matching account
  has_one :user, class_name: 'User'

  #...
end

class UserBuyerProfile < ActiveRecord::Base
  belongs_to :user_account
  validates_presence_of :user_account_id

  # ...
end

class UserSupplierProfile < ActiveRecord::Base
  belongs_to :user_account
  validates_presence_of :user_account_id

  #...
end

class User < ActiveRecord::Base
  define_method(:readonly?) { true }
  self.primary_key = 'id'

  # ...
end
```

**Fabricator**
```ruby
Fabricator(:user_account) do
  first_name { Faker::Name.name.split(' ').first }
  last_name  { Faker::Name.name.split(' ').last }
  email      { |attrs|
    Faker::Internet.email((attrs[:first_name] + ' ' + attrs[:last_name]).parameterize)
  }
  password { '12341234' }
  password_confirmation { '12341234' }
  terms_of_service { true }
  confirmed_at { 1.day.ago }
end

Fabricator(:buyer_user, from: :user_account, aliases: [:user]) do
  after_create do |user_account, _transients|
    Fabricate(:user_buyer_profile, user_account: user_account)
  end
end

Fabricator(:supplier_user, from: :user_account) do
  after_create do |user_account, _transients|
    Fabricate(:user_supplier_profile, user_account: user_account)
  end
end
```

As you can see, calling `Fabricate(:user)`, creates a `UserAccount` and `UserBuyerProfile` objects, which is what we need to have a fully functional user in our system. But right now we have to do this in our tests to return the user object: `Fabricate(:user) { Fabricate(:user).user }`, ideally I want to be able to do this instead: `Fabricate(:user) { Fabricate(:user) }`.

Hence, proposed callback - `on_create_return`.
In this particular example it would be used like this:

```ruby
Fabricator(:buyer_user, from: :user_account, aliases: [:user]) do
  after_create do |user_account, _transients|
    Fabricate(:user_buyer_profile, user_account: user_account)
  end
  on_create_return { |user_account| user_account.user }
end
```

This callback would be executed after all other callbacks are done.

I want stress though, there might be a better options how to achieve this, I am open to suggestions! Maybe there is existing functionality that allows to achieve similar results, but I could't figure it out from reading the docs.

Also I 100% agree with you that the same pattern might be useful, when you have a PORO object that encapsulates several AR objects.

**Comment by paulelliott** [comment]
I think you could pretty easily accomplish this with a simple helper in your own test suite.

```
# spec/helpers/fabricate_user.rb
def fabricate_user(:buyer, properties={})
  # make the things, look up the user, and return it
end
```

I totally get what you're suggesting and think what you're saying makes sense. I'm only hesitant to add this to fabrication because no one has ever asked for this sort of thing before.

**Comment by ixti** [comment]
I think that bloating fabrication with edge-case specific API is bad. Personally I solve this with solution similar to what @paulelliott proposed.
