### ISSUE TITLE
Fabricator rand minimum?

### ISSUE THREAD

**Issue by pedroadame** [paulelliott/fabrication#292]
It's OK to have a parameter that randomizes count between 1 and N, but it could be great to have the possibility of specify a minimum other than one.

**Comment by paulelliott** [comment]
It would be cool if you could pass it a range as well as just an integer. Any interest in making a PR?

**Comment by jaysonvirissimo** [comment]
Does [this](https://github.com/jaysonvirissimo/fabrication/blame/master/lib/fabrication/schematic/attribute.rb#L56) existing functionality work for your use case @pedroadame?

**Comment by ixti** [comment]
@jaysonvirissimo existing functionality requires to be way too verbose :D

On the other hand, I really don't see why fabrication needs this functionality (even existing rand helpers) seem a bit overkill. `::Kernel.rand` provides pretty simple interface:

``` ruby
rand(6) # random number in range 1..6
rand(6..9) # random number in range 6..9
```

**Comment by ixti** [comment]
I mean compare this:

``` ruby
Fabricator(:person) do
  open_source_projects(rand: 5)
  children(rand: 3) { |attrs, i| Fabricate(:person, name: "Kid #{i}") }
end
```

to:

``` ruby
Fabricator(:person) do
  open_source_projects(rand 5)
  children{ |attrs| Fabricate(:person, name: "Kid #{rand 3}") }
end
```

Probably I miss something. But I would simply deprecate this feature :D

**Comment by ixti** [comment]
Ignore me. I just realized that those are not "equivalents" I guess.

**Comment by ixti** [comment]
@pedroadame, as @jaysonvirissimo said, you can achieve that by:

``` ruby
children(:start_range => 42, :end_range => 69) { ... }
```

But I'm gonna open a PR with allowing to pass range to rand like this:

``` ruby
children(:rand => 42..69) { ... }
```
