### ISSUE TITLE
Find models in another folder

### ISSUE THREAD

**Issue by thiagoramos23** [paulelliott/fabrication#299]
Hi guys! First of all, this gem is really great. 

Could you guys help me understand how could I inform to the gem that I have my active record models locating in another folder? 
I have a grape/ruby app and my models are inside /infrastructure/models folder not at app/models like traditional rails app.

Is this a configurable thing?

Thanks a lot.

**Comment by paulelliott** [comment]
Hey there! Fabrication doesn't load any actual models. It only loads your fabricator definitions. You'll need to check the docs for grape to see how to configure its load path.
