### ISSUE TITLE
Models with deep namespace

### ISSUE THREAD

**Issue by thiagoramos23** [paulelliott/fabrication#301]
Hi guys, awesome work with this lib, thank you a lot.
I am having some trouble now that I have my models deep nested with namespaces and they are not on app/models folder.
Here is the example:

I have a model at: MY_APPLICATION_ROOT_FOLDER/infrastructure/models/sales/charge.rb
My model:
```ruby
 module Infrastructure
    module Models
      module Sales
        class Charge < ::ActiveRecord::Base
          self.table_name = 'charges'
        end
      end
    end
  end
```

And my fabricator at spec/fabricators/charge_fabricator.rb

```ruby
Fabricator(:infrastructure_models_sales_charge, aliases: [:sales_charge], class_name: "::Infrastructure::Models::Sales::Charge") do
  attributes...
end
```

And I am getting a weird error saying:

> uninitialized constant Infrastructure::Models::Sales

Am I doing something wrong?

**Comment by thiagoramos23** [comment]
Since I am not using rails and autoloading everything. I forgot that I need to require files.

**Comment by paulelliott** [comment]
Glad you figured it out! I think we've all been bitten by that at some point.
