### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by mallowigi** [paulelliott/fabrication#311]
If then, what are the alternatives?

If not, why is the documentation outdated?

**Comment by paulelliott** [comment]
This project is not dead and the documentation should not be outdated. Did you find an inaccuracy?

**Comment by mallowigi** [comment]
Because I just wasted hours trying to figure out the inverse_of, until I found out in the commit history that it has been reverted

**Comment by mallowigi** [comment]
Thanks. But since you're here, do you have any idea how can I circumvent this behavior? I have an entity, A, that `has_many` B. And I have an entity C that `has_many` B as well. However B is not a simple relationship table, it has properties as well, so I need to create it when creating A.

Putting `b { Fabricate(:B, a: nil) }` returns an error that a must be defined.

**Comment by mallowigi** [comment]
Sorry for bothering. But why did you remove it ?

**Comment by mallowigi** [comment]
NVM that
