### ISSUE TITLE
Site fabricationgem.org down: SSL issues?

### ISSUE THREAD

**Issue by berkes** [paulelliott/fabrication#319]
Looks like the site is down. DNS points to 216.239.32.21, which is still up and listening on port 80.

**Comment by paulelliott** [comment]
Both urls are working for me. Are you still seeing it?

**Comment by berkes** [comment]
Ah, It was an SSL error, but on my side: https-everywhere redirected to the HTTPS version, which is broken. The HTTP/plain version works.

**Comment by berkes** [comment]
Wait, on further inspection: www.fabricationgem.org works with SSL, but not fabricationgem.org. So it probably is a minor conflict somewhere in your redirects from non-www to www and from non-https to https.

**Comment by paulelliott** [comment]
Ah, I'm seeing it now. If you go to https://fabricationgem.org it fails. https://www.fabricationgem.org works properly though.

**Comment by paulelliott** [comment]
Thanks for pointing this out. I'll take a look at the DNS setup and get it straightened out!

**Comment by paulelliott** [comment]
Should be good to go now. Thanks again!
