### ISSUE TITLE
How to fabricate for polymorphic association?

### ISSUE THREAD

**Issue by millisami** [paulelliott/fabrication#53]
The following is the associations for my app model:

``` ruby
class Gallery < ActiveRecord::Base
  belongs_to :galleried, :polymorphic => true
  has_many :photos, :dependent => :destroy
end

class Photo < ActiveRecord::Base
  belongs_to :gallery
end

class Event < ActiveRecord::Base
  has_one :gallery, :as => :galleried, :dependent => :destroy
end

class Place < ActiveRecord::Base
  has_one :gallery, :as => :galleried, :dependent => :destroy
end
```

And the fabrications `fabricators.rb`

``` ruby
Fabricator(:gallery)  do
  galleried!{Fabricate(:place)}
end

Fabricator(:gallery_place, :from => :gallery) do
  galleried!{Fabricate(:place)}
end

Fabricator :photo do
  gallery!
end
```

The problem is with the fabricator for gallery. I'd to use `Fabricate(:place)` or `Fabricate(:event)` which can't be done coz its polymorphic model.

``` ruby
Fabricator(:gallery)  do
  galleried!{Fabricate(:place)}
end
```

How can I handle this?

**Comment by AlexVPopov** [comment]
Sorry for opening an old topic, but I'd like to bring it one step further. So, to continue the example - defining two gallery fabricator works, but how do you define the fabricators for `Event` and `Place`. If they don't contain `gallery`:
```ruby
Fabricator(:event) do

end
```
then:
```ruby
event = Fabricate :event
event.gallery # => nil
```
However, if we define them with `gallery`:
```ruby
Fabricator(:event) do
  gallery
end
```
then
```ruby
event = Fabricate :event # => SystemStackError: stack level too deep
```

**Comment by paulelliott** [comment]
Your gallery fabricator defines event and event defines gallery, hence the stack level too deep. Give this a shot:

Fabricator(:event) do
  gallery { Fabricate.build(:gallery, galleried: nil) }
end

If you force the gallery's reverse association to nil it should work like you expect.

**Comment by AlexVPopov** [comment]
Yes, this works perfectly. Thank you. How can I contribute this to the documentation?

**Comment by paulelliott** [comment]
The doc site has a separate repo (paulelliott/fabrication-site). There is a markdown file in there defining all the docs.

**Comment by AlexVPopov** [comment]
Btw, shouldn't the correct code be:
```ruby
Fabricator(:event) do
  gallery { Fabricate.build(:event_gallery, galleried: nil) }
end
```
?

**Comment by paulelliott** [comment]
Yeah, looks that way.
